#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
echo -e "${YELLOW}42... there's just something about that number"
echo -e "${BLUE}..."
echo -e "${GREEN}Aha, 42, I knew it!"
echo -e "${BLUE}Now--- er"
echo -e "${RED}What was the question again?"